### ISSUE TITLE
pt-speaker

### ISSUE THREAD

**Issue by wstevens0n** [rricharz/pi-top-install#14] opened 2017-07-18 06:35 UTC
Hey rricharz,

I finally got around to dusting off my pi-top and started following your instructions as I did many months ago.

It seems this guide is no longer up to date and I am having issues getting the speakers working a few seconds after boot. I know the speakers work because I hear sound about 3 seconds into the boot sequence video (Retropie)

I've attached a copy of the new pt-speaker code (as a text file) that's installed after running sudo apt-get pt-speaker. Saved now as /usr/bin/pt-peripherals-daemon.

[pt-peripherals-daemon.txt](https://github.com/rricharz/pi-top-install/files/1154870/pt-peripherals-daemon.txt)

I am having a hard time modifying the code in order to suite my needs. But until a fix is created do you could supply a location where I can simply view the old pt-speaker logic?

Thanks.

**Comment by m-roberts** [comment] 2017-07-18 12:19
Hi - Mike from pi-top here. I have just taken a look at this for you, and can confirm that there seems to be an issue with this.
I apologise for the disruption - we've just migrated to a new method of handling peripherals, and it seems that a regression occurred somehow.
We've started to take a look at this for you.. it should be fixed soon :)

**Comment by rricharz** [comment] 2017-07-18 13:03
Thanks Mike. I appreciate your help on this issue. I am travelling currently and cannot look into this for the next two weeks.

**Comment by wstevens0n** [comment] 2017-07-18 13:35
Thanks for your help Mike and safe travels rricharz!

**Comment by m-roberts** [comment] 2017-07-19 09:37
Hi guys - we have identified the issue:`hdmi_drive=2` needs to be set in `/boot/config.txt`.

@wstevens0n - to get started with pi-topSPEAKER, `sudo apt-get update`, `sudo apt-get install pt-speaker`, and then make the fix to your `config.txt`.
We are including this in the next update of the software, but you can do this yourself and it should just work after that. Let me know if you have any further issues.

@rricharz, if you would like, I would be happy to discuss with you how we have changed approach. We are working to make it as easy to install the software on Raspbian as it is on pi-topOS - now you can just install `pt-speaker` (from Raspberry Pi's repo!) and it should work out-of-the-box.

:)

**Comment by wstevens0n** [comment] 2017-07-19 13:13
![20170719_080829](https://user-images.githubusercontent.com/25314348/28368323-9466a998-6c59-11e7-94e4-278444f8560f.jpg)

@m-roberts I have actually made that modification previously and it did not fix the issue. I have attached a screenshot of what happens when I manually execute the new daemon. 

Again the speakers work for maybe 2-3 seconds than cut out completely.

**Comment by m-roberts** [comment] 2017-07-19 13:27
Hi - I'm sorry that you're still experiencing problems.

The fact that you are experiencing problems *after* getting audio out is very peculiar. Once the device is configured, it should 'just work'.
We are currently only testing pi-topOS and Raspbian - I'm not particularly well-versed in RetroPie, but I wonder if this is an image that you've had for a while, which might have other processes running that could be doing something

Are you able to confirm that this is happening on a newly burnt SD card?

**Comment by wstevens0n** [comment] 2017-07-19 13:45
No I haven't tried a new sd card and would prefer to refrain.

The fit is super tight with everything installed and I'd rather not open the case to remove the modules again.

![20170719_083215](https://user-images.githubusercontent.com/25314348/28369309-d350b164-6c5c-11e7-96b8-f31f9e6b8e09.jpg)

Is the prior screenshot not enough information to diagnose it?

If you can point me in the direction of where "writing config data to the pi-topspeaker" begins maybe I can look into that.

There's a definite issue in the new code because the old pt-speaker worked perfect.

**Comment by m-roberts** [comment] 2017-07-19 14:07
With regards to the terminal screenshot with the response from the daemon, everything is coming back as expected. Those last 3 lines (enabling write, writing config data, disabling write) are coming from `python-pt-speaker`, which the daemon is using to perform the initialisation as was done with the previous implementation.

`.speaker` is not meant to be a folder - it's just a file that allows for easy external identification of whether or not the device is detected.

And whilst I understand why you believe that it is the new code, the actual functions that are run when the device is detected are identical. Given that detection is working, it seems unlikely to be an initialisation problem.

Instead, I am interested to know if it's something to do with how it's behaving with possible remnants of the old speaker code, for example. This is why I was asking about a clean SD card - not as a solution, but rather as a test case.

**Comment by wstevens0n** [comment] 2017-07-20 03:08
Good day all!

I seemed to fix the issue today, what I did was modify the alsamixer volume down from 100% to 76%. 

I had some feeling that volume was high thus causing the speakers to cut out completely. 

Regarding the old pt-speaker code it was never installed originally on my sd card.

Again thanks for looking into this!

**Closed** 2017-07-20 05:52 UTC
